In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
import numpy as np
a=np.array([[1,2],[2,3],[4,5]])
print(a)

[[1 2]
 [2 3]
 [4 5]]


In [14]:
#reshape

import numpy as np
a=np.array([[1,2],[2,3],[4,5]])
print(a.reshape(6,1))

[[1]
 [2]
 [2]
 [3]
 [4]
 [5]]


In [24]:
#zeros

print(np.zeros((2,4)))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [22]:
#ones

print(np.ones((3,3)))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [34]:
#random

import numpy as np
a=np.array([[1,2],[2,3],[4,5]])
print(np.floor(100*np.random.random((3,2))))

[[ 27.  69.]
 [ 51.  45.]
 [ 34.  56.]]


In [32]:
#linespace

a=np.linspace(2,3,4)
print(a)

[ 2.          2.33333333  2.66666667  3.        ]


In [40]:
#matrix transpose

import numpy as np
a=np.array([[1,2],[2,3],[4,5]])
print("Before Transpose")
print("----------------")
print(a)
print("\nAfter Transpose")
print("----------------")
print(a.transpose())

Before Transpose
----------------
[[1 2]
 [2 3]
 [4 5]]

After Transpose
----------------
[[1 2 4]
 [2 3 5]]


In [41]:
#matrix multiplication

import numpy as np
a=np.array([[1,2],[2,3]])
b=np.array([[2,4],[3,2]])
print(a)
print("*")
print(b)
print("=")
print(a.dot(b))

[[1 2]
 [2 3]]
*
[[2 4]
 [3 2]]
=
[[ 8  8]
 [13 14]]


In [2]:
#svd

import numpy as np
from scipy.linalg import svd
x=np.array([[1,2,3],[4,5,6],[5,6,7]])
u,s,t=svd(x)
print("x=",x)
print("u=",u)
print("s=",s)
print("t=",t)

x= [[1 2 3]
 [4 5 6]
 [5 6 7]]
u= [[-0.25775879  0.94609665  0.19611614]
 [-0.62014124 -0.00634259 -0.78446454]
 [-0.74093539 -0.32382234  0.58834841]]
s= [  1.41499421e+01   8.82688844e-01   6.73489881e-17]
t= [[-0.4553376  -0.5697434  -0.6841492 ]
 [-0.79120225 -0.09341194  0.60437836]
 [-0.40824829  0.81649658 -0.40824829]]
